### ISSUE TITLE
Not idiomatic for ES6

### ISSUE THREAD

**Issue by julien-f** [floatdrop/create-error-class#1]
You should provide a base class which can be extended to provide a more idiomatic way to create custom error.

ES6 provides a way to extend built-in classes like `Error` but it does not work with transpilers such as Babel (see [caveats](https://babeljs.io/docs/advanced/caveats/)).

Feel free to take interesting parts from my own library [make-error](https://github.com/julien-f/js-make-error).
(If this module cover my needs, I am willing to deprecate mine.)

And please, try to make it work as much as possible in engines other than V8 :)

**Comment by floatdrop** [comment]
@julien-f thank you! Will defiantly look at this closer.

**Comment by floatdrop** [comment]
@julien-f I've replaced Error.captureStackTrace with ponyfill from `make-error` and `inherit`, so now it should work outside V8.

**Comment by julien-f** [comment]
Nice :)

**Comment by julien-f** [comment]
I think this issue can be closed :)
